"""
recommendations collection

Stores the deterministic output of the recommendation engine for a given
assessment. The `score_breakdown` and `explanation_points` are generated by
RULE-BASED CODE — the ai_explanation field is the ONLY part of this
document that comes from the AI layer, and it explains rather than decides.
"""

from datetime import datetime
from mongoengine import (
    Document,
    EmbeddedDocument,
    EmbeddedDocumentField,
    EmbeddedDocumentListField,
    StringField,
    FloatField,
    ReferenceField,
    DateTimeField,
    ListField,
)

from app.models.user import User
from app.models.assessment import Assessment


class ScoreBreakdown(EmbeddedDocument):
    academic_fit = FloatField(required=True)  # 0-40
    interest_fit = FloatField(required=True)   # 0-25
    skills_fit = FloatField(required=True)     # 0-20
    career_fit = FloatField(required=True)     # 0-15


class CourseRecommendation(EmbeddedDocument):
    course_name = StringField(required=True)
    match_score = FloatField(required=True, min_value=0, max_value=100)
    score_breakdown = EmbeddedDocumentField(ScoreBreakdown)

    # Plain-language reasons generated by rule-based logic
    # (e.g. "Strong Mathematics (A1/B2)", "Matches Software Engineering goal")
    explanation_points = ListField(StringField())

    # Optional AI-generated narrative wrapping the explanation_points in
    # friendlier prose — NEVER changes the score or ranking.
    ai_explanation = StringField()

    admission_category = StringField(
        choices=["Safe Choice", "Competitive Choice", "Reach Choice"]
    )


class Recommendation(Document):
    user = ReferenceField(User, required=True)
    assessment = ReferenceField(Assessment, required=True)

    results = EmbeddedDocumentListField(CourseRecommendation)  # top 10, ranked

    created_at = DateTimeField(default=datetime.utcnow)

    meta = {
        "collection": "recommendations",
        "indexes": ["user", "assessment", "-created_at"],
    }
