"""
recommendations collection

Stores the deterministic output of the recommendation engine for a given
assessment. The `score_breakdown` and `explanation_points` are generated by
RULE-BASED CODE — the ai_explanation field is the ONLY part of this
document that comes from the AI layer, and it explains rather than decides.
"""

from datetime import datetime
from mongoengine import (
    Document,
    EmbeddedDocument,
    EmbeddedDocumentField,
    EmbeddedDocumentListField,
    StringField,
    FloatField,
    ReferenceField,
    DateTimeField,
    ListField,
)

from app.models.user import User
from app.models.assessment import Assessment
from bson import ObjectId


class ScoreBreakdown(EmbeddedDocument):
    academic_fit = FloatField(required=True)  # 0-40
    interest_fit = FloatField(required=True)   # 0-25
    skills_fit = FloatField(required=True)     # 0-20
    career_fit = FloatField(required=True)     # 0-15


class CourseRecommendation(EmbeddedDocument):
    course_name = StringField(required=True)
    match_score = FloatField(required=True, min_value=0, max_value=100)
    score_breakdown = EmbeddedDocumentField(ScoreBreakdown)

    # Plain-language reasons generated by rule-based logic
    # (e.g. "Strong Mathematics (A1/B2)", "Matches Software Engineering goal")
    explanation_points = ListField(StringField())

    # Optional AI-generated narrative wrapping the explanation_points in
    # friendlier prose — NEVER changes the score or ranking.
    ai_explanation = StringField()

    admission_category = StringField(
        choices=["Safe Choice", "Competitive Choice", "Reach Choice"]
    )


class Recommendation(Document):
    user = ReferenceField(User, required=True)
    assessment = ReferenceField(Assessment, required=True)

    results = EmbeddedDocumentListField(CourseRecommendation)  # top 10, ranked

    created_at = DateTimeField(default=datetime.utcnow)

    meta = {
        "collection": "recommendations",
        "indexes": ["user", "assessment", "-created_at"],
    }


# Compatibility helpers for code that uses raw `db.recommendations` inserts
def create_recommendation_doc(user_id: str, result: dict) -> dict:
    """Return a plain dict suitable for inserting into the `recommendations` collection.
    This is a compatibility shim for parts of the codebase that use raw PyMongo inserts
    instead of the mongoengine `Recommendation` document above.
    """
    return {
        "_id": ObjectId(),
        "student_id": user_id,
        "student_aggregate": result.get("student_aggregate"),
        "shs_program": result.get("shs_program"),
        "mode": result.get("mode"),
        "top_courses": result.get("top_courses", []),
        "ai_summary": result.get("ai_summary"),
        "generated_at": datetime.utcnow(),
    }


def serialize_recommendation(r: dict) -> dict:
    """Serialize a raw recommendation document (from PyMongo) to a JSON-friendly dict.
    Works with documents created by `create_recommendation_doc` or legacy raw inserts.
    """
    return {
        "id": str(r["_id"]),
        "student_id": r.get("student_id"),
        "student_aggregate": r.get("student_aggregate"),
        "shs_program": r.get("shs_program"),
        "mode": r.get("mode"),
        "top_courses": r.get("top_courses", []),
        "ai_summary": r.get("ai_summary"),
        "generated_at": r.get("generated_at").isoformat() if r.get("generated_at") else None,
    }
